apiVersion: v1
kind: Service
metadata:
  name: {{ template "seleniumGrid.chromeNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: selenium-chrome-node
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - name: tcp-chrome
      protocol: TCP
      port: {{ .Values.chromeNode.seleniumServicePort }}
      targetPort: {{ .Values.chromeNode.seleniumPort }}
      {{- if .Values.chromeNode.noVnc.enabled }}
    - name: novnc-http
      protocol: TCP
      port: 7900
      targetPort: 7900
      {{- end }}
